name: Build and Push on Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build, Test, and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Run tests via Makefile (uses Docker Compose)
        run: |
          make ci

      - name: Build production image
        run: |
          make build

      - name: Push image to Docker Hub
        run: |
          make push