name: Build and Push
on:
  push:
    branches:
      - main 
      - my-new-branch

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Install dependencies
        run: docker compose -f docker-compose.yml run --rm app make setup

      - name: Run tests
        run: docker compose -f docker-compose.yml up --abort-on-container-exit

      - name: Build production image
        run: docker compose -f docker-compose.yml build app

      - name: Push image to Docker Hub
        run: docker compose -f docker-compose.yml push app